name: Daily CSV Update

on:
  schedule:
    # Runs daily at 1am PT / 10am UTC on Monday morning
    # See: https://crontab.guru/#0_11_*_*_1
    - cron: "0 10 * * *"
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  process_csv:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: make install

      - name: Update CSV
        run: make update-csv

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
